Migrate to Jakarta EE 9
FasterXML/jackson-jaxrs-providers pull request #124
Opened 2020-05-23 16:18 UTC by tamersaadeh

Jakarta EE 9 platform renames all the "old" namespaces from javax.* to jakarta.*. This pull request performs this migration so that when Jacakrta EE 9 is released in [June 2020](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan#proposed-progress-reviews) it will be compatible.

I ran mvn test and [travis builds](https://travis-ci.com/github/tamersaadeh/jackson-jaxrs-providers) with no failures*.

Note 1: this is completely incompatible with the old namespace, so probably the major version of the library should be bumped.
Note 2: currently depends on pre-released versions of the JAXB specification (RC3). This can be updated when the final version is released.
Note 3: this PR is similar to my PR for FasterXML/jackson-modules-base#95 and FasterXML/jackson-dataformat-xml#407

*: I needed to modify 3 tests (7ff95e7a6195f85b83ebae46cc41970a52a7d89f) but I'm not exactly sure way this change was needed on my development PC.

2020-05-24 14:32 UTC, GedMarc commented on pom.xml
>      <version.jetty>9.4.17.v20190418</version.jetty>
9.4.29.v20200521

2020-06-01 08:05 UTC, tamersaadeh commented on pom.xml
>      <version.jetty>9.4.17.v20190418</version.jetty>
Sure I can update this, I just didn't think my commits should touch other dependency not strictly relevant to the pull request.

2020-10-15 07:23 UTC, fenixcitizen commented on json/src/moditect/module-info.java
> +    requires static jakarta.ws.rs.api;
I think this line and all similar in other `module-info.java` files should not change. See #127 and #121

2020-10-15 07:40 UTC, GedMarc requested changes
the static clauses in the moditect file are for backwards compatibility, 

don't change them, add new ones instead - this makes sure that when modules are used, it can be done easily

also jakarta artifacts should be a shade on the javax. ones, with the package replaced, it shouldn't be a source code change

2020-10-15 07:41 UTC, GedMarc commented
Nooooooooooooooooo big no on the moditect changes, don't think you understand what's happening there :)

2020-10-15 17:46 UTC, cowtowncoder commented
Just a quick comment: I have no plans to move ahead with this change at this point in time.
I am not against migration in principle but it does not sound like this could be done without significant breakage for existing users, for now.

2021-01-01 13:30 UTC, joschi commented
@tamersaadeh @cowtowncoder With the `jakarta.*` and `javax.*` namespaces existing in parallel, I think it would make sense to cater both ecosystems with `jackson-jaxrs-providers` because `javax.*` won't be vanishing over night.

What do you think?

2021-01-03 23:17 UTC, cowtowncoder commented
@joschi Agreed, and for 2.12 there is something like that (see #127) -- "jakarta" classifier for new variants.

2021-01-03 23:17 UTC, closed without merging

2021-01-04 08:05 UTC, joschi commented
> Agreed, and for 2.12 there is something like that (see #127) -- "jakarta" classifier for new variants.

As far as I understand #127 only addresses the JPMS module information but doesn't update the package imports in the actual source files, does it?

So we would need a second set of sources (`src/main/jakarta`?) with the appropriate imports from `jakarta.*`.

2021-01-04 16:25 UTC, GedMarc commented
no - it get's shaded in with all the imports correctly applied

2021-01-04 17:21 UTC, joschi commented
> no - it get's shaded in with all the imports correctly applied

@GedMarc Could you elaborate? I've checked out the `master` branch of this repository and ran `mvn install` but there are no artifacts using the Jakarta EE namespace implemented by Jersey 3.0.0 (only the default `jar` and the `no-metainf-services` artifacts).

I also only see Jersey 2.25.1 referenced in the POM files, not Jersey 3.0.0 (as of fcc3e957b9d9d71ead4765f9181df6b11f09d1ec):
https://github.com/FasterXML/jackson-jaxrs-providers/blob/fcc3e957b9d9d71ead4765f9181df6b11f09d1ec/pom.xml#L37

2021-01-04 17:25 UTC, GedMarc commented
No the code itself does not reference it,. it get's shaded in and all the relevant imports get modified into a classified artefact on pom, called "-jakarta", 

Look at https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html

This keeps a single code base, while enabling full jakarta usage.
The implementation is correct and complete, I forgot about the OSGi things will see if this has been pulled in or if I must do it quick 

You need to follow the readme and reference the jakarta classified artefacts.

2021-01-04 17:52 UTC, joschi commented
> No the code itself does not reference it,. it get's shaded in and all the relevant imports get modified into a classified artefact on pom, called "-jakarta",

Turns out that this is missing on the `master` branch and it's only available on the `2.12` branch.

2021-01-04 18:08 UTC, GedMarc commented
:D

Ok i think it might be waiting for the latest merge,
Although you make a good point...

@cowtowncoder are you targeting javax. for 3.0 release? Should I update the references?

2021-01-04 23:23 UTC, cowtowncoder commented
Ok, so the omission from `master` is an artifact of one `pom.xml` merge conflicts being ignored -- since that is a royal PITA when rolling forward changes after releasing new versions (since version numbers across branches will "conflict" when releases are made from maintenance branches).
Basically all changes to `pom.xml`s need to be manually merged.

As to 3.0 itself: I don't yet know, so probably the best thing to do would be to just merge functionality from `2.12`, and figure it out in future, based on success of Jakarta variant.